export const testData = {
  users: [
    {
      id: "KV4Lv9yUHtNVB42V0ZrFf",
      createdAt: 1645628972465,
      email: "test@test.com",
      password: "test",
    },
  ],
  inspections: [
    {
      id: "wS6UeppUQoiXGTzAI6XrM",
      name: "Inspection Paris 16eme",
      installationType: "Pipeline",
      constructionYear: 1951,
      company: "GRTgaz",
      type: "Bending Strain",
      diameter: "40cm",
      material: "Steel",
      coating: "Poly Ethylene",
    },
    {
      id: "Jkors1KGKA8Xk3-WIgKRW",
      name: "Inspection Marseille 7eme",
      installationType: "Pipeline",
      constructionYear: 1967,
      company: "Total",
      type: "River crossing",
      diameter: "47cm",
      material: "Cast Iron",
      coating: "Epoxy",
    },
    {
      id: "2LJ_sgmy_880G9WivH5Hf",
      name: "Inspection Bordeaux-Mérignac",
      installationType: "Pipeline",
      constructionYear: 1991,
      company: "Shell",
      type: "Mapping",
      diameter: "40cm",
      material: "Steel",
      coating: "Poly Ethylene",
    },
    {
      id: "dY8Q5uXxRtyH55sxThr_B",
      name: "Inspection Toulouse Ile du Ramier",
      installationType: "Pipeline",
      constructionYear: 1963,
      company: "Terega",
      type: "River crossing",
      diameter: "47cm",
      material: "Cast Iron",
      coating: "Epoxy",
    },
    {
      id: "fsOw03AoDm6do4udFZIbn",
      name: "Inspection Houston",
      installationType: "Pipeline",
      constructionYear: 1982,
      company: "Shell",
      type: "Mapping",
      diameter: "50cm",
      material: "Steel",
      coating: "Poly Ethylene",
    },
    {
      id: "vyXO36A_L_fkPFVlAFGNm",
      name: "Inspection Kansas City River",
      installationType: "Pipeline",
      constructionYear: 1969,
      company: "Chevron",
      type: "River crossing",
      diameter: "41cm",
      material: "Cast Iron",
      coating: "Epoxy",
    },
  ],
};
